### ISSUE TITLE
README: Clarify status of Pyan repos on GitHub

### ISSUE THREAD

**Issue by Technologicat** [Technologicat/pyan#17]
Due to [historical reasons](https://github.com/davidfraser/pyan/pull/9#issuecomment-525279644), there is constantly some confusion about the Pyan repositories.

To clear it up, in the next release, place something like this at the start of the README:

---

**Official Pyan repositories** (as of autumn 2019):

- [davidfraser/pyan](https://github.com/davidfraser/pyan): **stable** version.
- [Technologicat/pyan](https://github.com/Technologicat/pyan): **development** version. Looking to [report a bug](https://github.com/Technologicat/pyan/issues/new) or missing feature?

**Pyan no longer supports Python 2.x.** If you still need to analyze Python 2 code, the stable repo has an archive of [the final version of Pyan2](https://github.com/davidfraser/pyan/tree/pre-python3).

The **PyPI package** [pyan3](https://pypi.org/project/pyan3/) is built from **development**.

Development is manually synced to stable (via a PR) every now and then.

*To future maintainers: when you take over, please update the link to the active development repo, and the date.*

**Comment by edumco** [comment]
I think i can help update the repo readme. What do you think about it?

**Comment by Technologicat** [comment]
Sure, why not!

Just send a PR when done, and I'll merge it.
