### ISSUE TITLE
Usage section on github mentions pyan.create_callgraph() but there seems to be no such function

### ISSUE THREAD

**Issue by Synaps3** [Technologicat/pyan#44]
Trying to use the package via script as suggested in the usage section should work, but errors as it can't find the method.

**Comment by johnyf** [comment]
Using #43, i.e., the branch https://github.com/johnyf/pyan/tree/typing (to avoid a bug that would prevent importing the package), the following works:

```python
from pyan import create_callgraph
```

Please note that the repository is ahead of the version currently available through the [Python Package Index (PyPI)](pypi.org/).

**Comment by Synaps3** [comment]
Thanks! Could you update the font page guide to indicate that the needed code is not in the package index version yet?

**Comment by johnyf** [comment]
I do not have write access to this repository, and also the documentation will correspond to the package when the next PyPI release occurs.

**Comment by Synaps3** [comment]
> 
> 
> I do not have write access to this repository, and also the documentation will correspond to the package when the next PyPI release occurs.



> 
> 
> Using #43, i.e., the branch https://github.com/johnyf/pyan/tree/typing (to avoid a bug that would prevent importing the package), the following works:
> 
> ```python
> from pyan import create_callgraph
> ```
> 
> Please note that the repository is ahead of the version currently available through the [Python Package Index (PyPI)](https://pypi.org/).

So I just got around to running this and it still has code like:

print foo()

I thought the print keyword was deprecated in python2? Are you sure this code is python3 compatible?  It does not run for me.

**Comment by johnyf** [comment]
Please see https://github.com/johnyf/pyan/issues/8#issuecomment-698600360 (I couldn't find any old-style `print` statements).

**Comment by Technologicat** [comment]
> I do not have write access to this repository, and also the documentation will correspond to the package when the next PyPI release occurs.

@johnyf : For a while already, you've been more active about `pyan` than me. I've invited you as a collaborator to this repository.

**Comment by johnyf** [comment]
Thank you for inviting me as a collaborator to this repository.

**Comment by Technologicat** [comment]
PyPI package `pyan3` updated. Please try again with the latest version, and reopen this issue if necessary.

**Comment by Technologicat** [comment]
@johnyf : You're welcome.
