### ISSUE TITLE
Invoking pyan3 from terminal gives pyan module not found error.

### ISSUE THREAD

**Issue by avijit1258** [Technologicat/pyan#45]
After pip installing pyan3, when I try to run `pyan3 --help`, I get the following error message. 
![Screen Shot 2020-09-17 at 3 34 18 PM](https://user-images.githubusercontent.com/10563596/93530980-bc6d9780-f8fb-11ea-8a01-8c5900f53380.png)

**Comment by johnyf** [comment]
Please see https://github.com/Technologicat/pyan/issues/19#issuecomment-691599078. Installing from the repository avoids this issue.

**Comment by Technologicat** [comment]
The PyPI package is out of date at the moment. I'll fix it when I have the chance. I'll likely wait until #31 is merged, so that we'll get relative import support.

**Comment by Technologicat** [comment]
PyPI package `pyan3` updated. Please try again with the latest version, and reopen this issue if necessary.
