### ISSUE TITLE
pyan3 cannot run

### ISSUE THREAD

**Issue by gladcolor** [Technologicat/pyan#46]
I tried to make an html output using:
pyan *.py --uses --no-defines --colored --grouped --annotated --html > myuses.html

returned:
Usage: pyan FILENAME... [--dot|--tgf|--yed]
pyan: error: no such option: --html

 
When run command: pyan3 -help
the result is:
Traceback (most recent call last):
  File "/home/yuan/anaconda3/envs/pyan3/bin/pyan3", line 7, in <module>
    from pyan import main
ImportError: cannot import name 'main'

run pyan -h:

Usage: pyan FILENAME... [--dot|--tgf|--yed]

Analyse one or more Python source files and generate anapproximate call graph
of the modules, classes and functions within them.

Options:
  -h, --help            show this help message and exit
  --dot                 output in GraphViz dot format
  --tgf                 output in Trivial Graph Format
  --yed                 output in yEd GraphML Format
  -f FILE, --file=FILE  write graph to FILE
  -l LOG, --log=LOG     write log to LOG
  -v, --verbose         verbose output
  -V, --very-verbose    even more verbose output (mainly for debug)
  -d, --defines         add edges for 'defines' relationships [default]
  -n, --no-defines      do not add edges for 'defines' relationships
  -u, --uses            add edges for 'uses' relationships [default]
  -N, --no-uses         do not add edges for 'uses' relationships
  -c, --colored         color nodes according to namespace [dot only]
  -G, --grouped-alt     suggest grouping by adding invisible defines edges
                        [only useful with --no-defines]
  -g, --grouped         group nodes (create subgraphs) according to namespace
                        [dot only]
  -e, --nested-groups   create nested groups (subgraphs) for nested namespaces
                        (implies -g) [dot only]
  --dot-rankdir=RANKDIR
                        specifies the dot graph 'rankdir' property for
                        controlling the direction of the graph. Allowed
                        values: ['TB', 'LR', 'BT', 'RL']. [dot only]
  -a, --annotated       annotate with module and source line number
  --make-svg            try to run dot to make svg automatically

**Comment by Technologicat** [comment]
The PyPI package is currently out of date (see #50).

Until I get it fixed, please clone and install `pyan` from GitHub. HTML export is available in the version on GitHub.

**Comment by Technologicat** [comment]
PyPI package `pyan3` updated. Please try again with the latest version, and reopen this issue if necessary.
