### ISSUE TITLE
Publish package on Pypi?

### ISSUE THREAD

**Issue by m-aciek** [Technologicat/pyan#6]
Hi @Technologicat, thank you for great work on that!

Do you consider adding package on Pypi with pyan in the future?

**Comment by Technologicat** [comment]
Yes, good idea!

Thanks for the suggestion, I'll make a ``setup.py`` and package this the next time I hack on ``pyan``.

**Comment by Technologicat** [comment]
Done. [PyPI page here](https://pypi.org/project/pyan3/).
