### ISSUE TITLE
Breaking the fork

### ISSUE THREAD

**Issue by jdb78** [Technologicat/pyan#69]
As this repo has developed a fair bit compared to davidfraser/pyan, I suggest we cut the fork.

**Comment by Technologicat** [comment]
I'm fine with the idea, but don't have a lot of time for `pyan` right now.

It's my impression that cutting forks (while preserving the issue tracker and other metadata) is done by contacting GitHub support. Would you like to handle this?

**Comment by jdb78** [comment]
On it

**Comment by Technologicat** [comment]
Thank you!
